### ISSUE TITLE
Mattermost dialog box doesn't auto-appear on interaction calls

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-plugin-chatops#5]
### Environment
* Python version:   3.8.5
* Nautobot version:   1.0.0b2
* nautobot-plugin-chatops version:   1.0.1

In Mattermost, when I run the command `/nautobot get-devices` command, and select "Name" from the Select a Device Filter selection menu, no dialog box appears.

### Steps to Reproduce
1.  In Mattermost, run the command `/nautobot get-devices`
2. In the Select a Device Filter menu, select "Name"

### Expected Behavior

A dialog box to appear, allowing me to type in the device name.

### Observed Behavior

I got a private message from the bot saying "If the dialog does not appear, copy this command and resend: /nautobot get-devices name"

Nothing else appeared after that.  However if I run that exact command listed, `/nautobot get-devices name`, a dialog box properly appears and I'm able to pull up a device.

**Comment by smk4664** [comment]
This is due to dialog's in mattermost only being able to be called from a slash command.  There is a 3 second window in which the interaction has to respond with the dialog.  This could possibly be extended by using the response_url and storing the original trigger_id from the initial slash command.  Here are details from the documentation... https://developers.mattermost.com/integrate/slash-commands/#what-if-my-slash-command-takes-time-to-build-a-response

**Comment by smk4664** [comment]
I got an update from Mattermost that we are not returning a valid response to the interactive message submission. I will be investigating more this week to see if we can resolve this issue.
